#pragma once
// Auto-generated by TIMx PWM Tuner (ncurses)
#define APB_HZ        120000000
#define PPRE_DIV      2
#define TIM_BITS      32

#define TIM_PSC       2
#define TIM_ARR       9
#define TIM_CCR3      5
#define TIM_CCR4      5
#define TIM_CENTER    0  // 0=edge, 1=center
#define TIM_LOCK50    1

// Derived (for info): f_tim=240000000 Hz, f_pwm≈8000000 Hz
// N=ARR+1=10, duty3≈0.500000, duty4≈0.500000
